### ISSUE TITLE
only the pool that works.

### ISSUE THREAD

**Issue by joe83** [harodggg/aelo-mining-pool#18]
This already working? I can only start the pool, while the client, worker and apps not working yet.

**Comment by harodggg** [comment]
It will take a while. Been working on this repo for a while, a lot of work to do, and issues to fix @joe83

**Comment by harodggg** [comment]
In this way, if mining machines such as asic and fpga appear, we only need to connect them to the mining pool very simply. You can easily implement prover and join the mining pool without a lot of other work.

**Comment by harodggg** [comment]
aleo's code is not very mature, and friendly. We need more design and thinking to meet the needs as much as possible. At the same time, you also need to pay attention to the update of the aleo warehouse.

**Comment by joe83** [comment]
Great, thanks.
